server:
  port: 8080
spring:
  jpa:
    database: MYSQL
    show-sql: false
    hibernate:
      ddl-auto: create-drop
  datasource:
    url: "jdbc:mysql://mysqldb:3306/mentorship"
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver