server:
  port: 80
spring:
 jpa:
    database: MYSQL
    show-sql : true
    hibernate:
     ddl-auto : create-drop
 datasource:
        url: jdbc:mysql://localhost:3306/mentorship?create=true
        username: root
        password: root
        driver-class-name: "com.mysql.jdbc.Driver"
 activemq :
     in-memory : true
     packages:
      trust-all : true